### ISSUE TITLE
Segfault on memory deallocation

### ISSUE THREAD

**Issue by bbrelje** [mdolab/idwarp#12]
## Type of issue
What types of issue is it?
- Bugfix (non-breaking change which fixes an issue)

## Description
Commit 342d98fe0f57cc20e3c25f2f48efdb84dd61db40 removed the common_to_dxs VecScatterCreate function from initializeWarping.F90. However, the VecScatterDestroy destructor on line 49 of releaseMemory.F90 was not removed. PETSc therefore tries to destroy an uninitialized VecScatter object and segfaults. 

### Steps to reproduce issue
1. Compile idwarp using GCC 7, PETSc 3.11, and Sandy's fork of idwarp
2. cd idwarp/python/reg_tests
3. python solve_script.py test2
4. Redo with debug flags turned on and using Valgrind if desired to localize the error

### Current behavior
Segfaults

### Expected behavior
No segfault

### Code version (if relevant)
**Python version:** Miniconda 3.7

**External dependencies:**Petsc 3.11

**Internal packages:** idwarp latest Sandy fork

**Comment by nwu63** [comment]
This has been fixed as part of #13

**Comment by eirikurj** [comment]
Closing
