### ISSUE TITLE
call to VecGetValues causes build error?

### ISSUE THREAD

**Issue by ianbtr** [mdolab/idwarp#45]
I am trying to compile idwarp, but running `make` gives me the following error:

```
mpif90 -I../..//mod -I/home/---/CGNS-3.3.0/opt-gfortran/include -DUSECGNSMODULE   -fPIC -fPIC -fdefault-real-8 -O2 -I/home/---/petsc-3.14.3/include -I/---/petsc-3.14.3/real-opt/include -I/---/petsc-3.14.3 -c getCommonVolumeCoordinates.F90 -o ../..//obj/getCommonVolumeCoordinates.o
getdXs.F90:19.64:

     call VecGetValues(dXs, 1,  (/i+istart-1/), output(i), ierr)
                                                                1
Error: There is no specific subroutine for the generic 'vecgetvalues' at (1)
getSurfaceCoordinates.F90:20.67:

     call VecGetValues(Xs, 1, (/iStart+i-1/), coordinates(i), ierr)
                                                                   1
Error: There is no specific subroutine for the generic 'vecgetvalues' at (1)
```

The error refers to this line, and one other:
https://github.com/mdolab/idwarp/blob/68d9c299fb1b5a60d7fb920020071e3cee4921b5/src/warp/getdXs.F90#L19

Checking the [PETSc documentation](https://www.mcs.anl.gov/petsc/petsc-current/docs/manualpages/Vec/VecGetValues.html) for this function suggests that there should be 4 arguments when this function is called, not 5.  Could this be the source of the build error?

I am using `gfortran` 4.8.5 with PETSc version 3.14.3 and OpenMPI 4.1.0.

For some reason I can still successfully install the library using `pip install .` despite this error occurring, but then importing the library gives this warning message:

```
mca_base_component_repository_open: unable to open mca_op_avx: ---/openmpi-4.1.0/opt-gfortran/lib/openmpi/mca_op_avx.so: undefined symbol: ompi_op_base_module_t_class (ignored)
```

**Comment by nwu63** [comment]
Please read the docs for specific versions of dependencies that are supported. For example, we do not support PETSc 3.14.
