### ISSUE TITLE
Small Bugs in making idwarp_cs

### ISSUE THREAD

**Issue by GuardZ** [mdolab/idwarp#5]
src_cs/f2py/Makefile
In this file, there is no commands to generate ".f2py_f2cmap"
However, in the end, it comes with "rm .f2py_f2cmap"
Anything missing in the Makefile? Or it is just unnecessary.

**Comment by GuardZ** [comment]
The compiling results also show that:
rm: cannot remove ‘.f2py_f2cmap’: No such file or directory
make[2]: [all] Error 1 (ignored)

**Comment by johnjasa** [comment]
Could you please paste the full output of running `make` here?
Does idwarp finish compiling successfully or does it fail due to this error?

**Comment by GuardZ** [comment]
Actually, when you try to compile a 'complexified' version of the code: idwarp_cs, this mistake does not affect the process. 
In the end, it shows:
`Testing if module idwarp_cs can be imported...
Module idwarp_cs was successfully imported.
mv idwarp_cs.so ../../python
rm *.o
rm *.c
rm .f2py_f2cmap
rm: cannot remove '.f2py_f2cmap': No such file or directory
Makefile:17: recipe for target 'all' failed
make[2]: [all] Error 1 (ignored)
make[2]: Leaving directory '/home/guardmdo/repos/idwarp/src_cs/f2py'
make[1]: Leaving directory '/home/guardmdo/repos/idwarp'`
It still finish compiling successfully. 
However, I try to show that the commands 
'rm .f2py_f2cmap'
in the file
'src_cs/f2py/Makefile'
is unnecessary. 
Or the compiling process miss the generation of '.f2py_f2cmap'.

**Comment by johnjasa** [comment]
Thanks for the additional detail.
It looks like this is an unnecessary command in your case, but may be necessary for other build cases.
I found a comment in the code that it is needed in some cases, so we'll keep it there for now.
