### ISSUE TITLE
problem installing idwarp 

### ISSUE THREAD

**Issue by m-meliani** [mdolab/idwarp#9]
I am trying to install idwarp, I am using the same packages that I used to install adflow successfully (?) (need idwarp to run the complete tests) and pyspline (same CGNS paths etc...).
The problem seems to occur at the end of the installation process when the 'make' tests the 'import idwarp'.

![image](https://user-images.githubusercontent.com/18448391/61731192-3f887180-ad7b-11e9-8a26-9a9fba03d906.png)

the problem seems to come from an: undefined symbol cg_elementdatasize_f_, which only seems to exist in binaries (so I couldn't investigate the problem further):

Binary file lib/libidwarp.a matches
Binary file obj/readUnstructuredCGNS.o matches
Binary file src/f2py/idwarp.so matches

Do you have an idea of what might be the problem?

PS: I'm on Ubuntu 18.04

**Comment by nwu63** [comment]
Hey Mostafa, can you attach the entire output of the build? That would help with the debug process.

**Comment by m-meliani** [comment]
Hey Neil!
I have attached a copy of the output of the make command.
[cp-output.txt](https://github.com/mdolab/idwarp/files/3426030/cp-output.txt)
Let me know if you need more info.

**Comment by nwu63** [comment]
I don't see anything out of the ordinary, what's your numpy version?

**Comment by m-meliani** [comment]
To my best knowledge my packages correspond to those suggested on the mdolab 3rd party packages page: http://mdolab.engin.umich.edu/docs/installInstructions/install3rdPartyPackages.html#install3rdpartypackages (numpy version 1.16.4, but I receive a deprecation message from the idwarp 'make' concerning numpy)

I am suspecting a bad interaction between python3 and python2 since python3 was my system default one (although I made sure to activate the python2 environment). I will make a new attempt after some cleaning and let you know.

**Comment by nwu63** [comment]
I see. You should check that the f2py/numpy paths and the python include directories are correct, they are printed out during compilation. The deprecation warning is nothing to worry about.

**Comment by m-meliani** [comment]
Hello! It finally works, I'm not exactly sure what solved it but I'll just leave a small description of what I did if anybody encounters the same problem:
- got rid of anaconda and just kept the default python2 (not to confuse my system)
- also discovered I had 2 cmake (the default one 3.10 and 3.14.5) so cleaned that to keep the latter
- I figured cg_elementdatasize_f_ should come from CGNS installation so I played a bit with that, specifically with the fortran naming naming option if you launch the ccmake command (uppercase, lowercase, etc...)
