### ISSUE TITLE
"Symbol ‘null’ at (1) has no IMPLICIT type" when compiling

### ISSUE THREAD

**Issue by haizhou0410** [mdolab/idwarp#91]
Hello everyone, when I compile idwarp, I met a error that says as follows. Does anyone know how to fix this? Thank you very much!
```
readUnstructuredCGNS.F90:185:85:
  185 |                                             zones(iZone)%sections(sec)%elemConn, NULL, ierr)
      |                                                                                     1
Error: Symbol ‘null’ at (1) has no IMPLICIT type; did you mean ‘cg_null’?
make[3]: *** [../..//Rules.mk:2: readUnstructuredCGNS.o] Error 1
```

### Steps to reproduce issue

1. …
2. …
3. …

### Current behavior
…

### Expected behavior
…

### Code versions

- Operating System: ubuntu
- Python:
- OpenMPI:
- CGNS: stable version
- PETSc:
- Compiler: gfortran
- This repository:

**Comment by eirikurj** [comment]
Hi, assuming you are using CGNS 4.4, then we [officially](https://mdolab-mach-aero.readthedocs-hosted.com/en/latest/installInstructions/install3rdPartyPackages.html) dont support it at the moment. However, there is an open PR https://github.com/mdolab/idwarp/pull/90 that will address this. For future reference, please take the time to populate the issue template appropriately, including full versions of each package, as this helps us address the issue quicker.
